from fpdf import FPDF
import os

def generate_pdf(user, measurement, output_path=None):
    """
    user: dict { id, name, age, gender, heightCm, weightKg, ... }
    measurement: dict { weightKg, heightCm, bmi, category }
    output_path: optional path to save file
    returns output_path
    """
    if output_path is None:
        output_path = f"bmi_report_{user.get('id','unknown')}.pdf"

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Arial", "B", 18)
    pdf.cell(0, 10, "BMI Report", ln=True, align="C")
    pdf.ln(6)

    pdf.set_font("Arial", size=12)
    pdf.cell(0, 8, f"Name: {user.get('name','-')}", ln=True)
    pdf.cell(0, 8, f"Age: {user.get('age','-')}", ln=True)
    pdf.cell(0, 8, f"Gender: {user.get('gender','-')}", ln=True)
    pdf.cell(0, 8, f"Height: {measurement.get('heightCm','-')} cm", ln=True)
    pdf.cell(0, 8, f"Weight: {measurement.get('weightKg','-')} kg", ln=True)
    pdf.cell(0, 8, f"BMI: {measurement.get('bmi','-')}", ln=True)
    pdf.cell(0, 8, f"Category: {measurement.get('category','-')}", ln=True)

    pdf.ln(8)
    pdf.set_font("Arial", "I", 10)
    pdf.multi_cell(0, 6, "Generated by Device-Aware BMI Studio. Please consult a healthcare professional for interpretation.")

    # ensure folder exists if path includes folders
    outdir = os.path.dirname(output_path)
    if outdir and not os.path.exists(outdir):
        os.makedirs(outdir, exist_ok=True)

    pdf.output(output_path)
    return output_path
